//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountClasificationRelation
    {
        public string AccountClasificationID { get; set; }
        public string Fk_AccountID { get; set; }
        public string Fk_ClasificationID { get; set; }
    
        public virtual AccountClasification AccountClasification { get; set; }
        public virtual CompanyAccount CompanyAccount { get; set; }
    }
}
