//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoDBEntities : DbContext
    {
        public CargoDBEntities()
            : base("name=CargoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountClasification> AccountClasification { get; set; }
        public virtual DbSet<AccountClasificationRelation> AccountClasificationRelation { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CompanyAccount> CompanyAccount { get; set; }
        public virtual DbSet<Condition> Condition { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Courier> Courier { get; set; }
        public virtual DbSet<CurrentWarehouseCodeNumber> CurrentWarehouseCodeNumber { get; set; }
        public virtual DbSet<DeliveryCompany> DeliveryCompany { get; set; }
        public virtual DbSet<Destination> Destination { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NotificationAccountRelation> NotificationAccountRelation { get; set; }
        public virtual DbSet<Origin> Origin { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostUser> PostUser { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<WarehouseTypeRelation> WarehouseTypeRelation { get; set; }
        public virtual DbSet<WarehouseTypes> WarehouseTypes { get; set; }
    }
}
