//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courier
    {
        public string CourierID { get; set; }
        public string Fk_WarehouseID { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public string TrackingNumber { get; set; }
        public string Fk_DeliveryCompany { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Units { get; set; }
        public string Fk_UnitType { get; set; }
        public bool Active { get; set; }
    
        public virtual DeliveryCompany DeliveryCompany { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
