//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentWarehouseCodeNumber
    {
        public int WarehHouseID { get; set; }
        public int WarehouseCodeNumber { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    }
}
