//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationAccountRelation
    {
        public string NotificationAccountRelation1 { get; set; }
        public string Fk_Account { get; set; }
        public string Fk_Notification { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CompanyAccount CompanyAccount { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
