//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostUser
    {
        public string PostUserID { get; set; }
        public string Fk_Post { get; set; }
        public string Fk_User { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Post Post { get; set; }
    }
}
